wandb_version: 1

batch_size:
  value: 32
drop:
  value: 0.5
epochs:
  value: 100
f1:
  value: 24
f2:
  value: 32
f3:
  value: 48
fc_layer_size:
  value: 1024
k:
  value: 5
learning_rate:
  value: 0.0001
