wandb_version: 1

batch_size:
  value: 32
epochs:
  value: 50
f1:
  value: 32
f2:
  value: 48
f3:
  value: 32
f4:
  value: 48
f5:
  value: 32
fc_layer_size:
  value: 512
learning_rate:
  value: 0.0001
