wandb_version: 1

batch_size:
  value: 16
epochs:
  value: 50
f1:
  value: 32
f2:
  value: 24
f3:
  value: 48
f4:
  value: 24
f5:
  value: 24
fc_layer_size:
  value: 128
learning_rate:
  value: 0.0001
